### ISSUE TITLE
Logical properties for directional effects

### ISSUE THREAD

**Issue by adactio** [WICG/view-transitions#46]
Exciting API! (especially for multi-page apps AKA websites)

I was wondering if the names of these effects might be open to change (or aliasing):
````
reveal-left
reveal-right
reveal-up
reveal-down
cover-left
cover-right
cover-up
cover-down
````
CSS has logical properties, which is particularly great for internationalisation. Could the same logic apply here?
````
reveal-inline-start
reveal-inline-end
reveal-block-start
reveal-block-end
cover-inline-start
cover-inline-end
cover-block-start
cover-block-end
````

**Comment by vmpstr** [comment]
We've considered semantic words like "next" and "previous" rather than "left" and "right" in #11, and also discussed internationalization there.  One difficulty with inline/block directions is that they may change depending on where you are in the DOM. Do you mean that an element would consider its DOM location and then pick a physical direction based on the logical one at the time of animation start?

**Comment by adactio** [comment]
Ooh, I have to admit I hadn't thought it through to the extent. I was really only considering the logical properties at the page level.

**Comment by vmpstr** [comment]
It makes sense: I think these direction are only really useful at the page level anyway, so perhaps we can use that. This is still somewhat in flux, so it's good to think about the right language to expose
